spring:
  datasource:
    url: jdbc:mysql:///mybatis?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis配置
mybatis:
  type-aliases-package: net.zm123.springmybatis.domain
  mapper-locations: classpath:net/zm123/springmybatis/mapper/*Mapper.xml
#config-location: