#yml多文档配置不同prifile

---
server:
  port: 8081
spring:
  profiles: dev
---
server:
  port: 8082
  spring:
    profiles: test
---
server:
  port: 8083
  spring:
    profiles: prod
---
spring:
  profiles:
    active: test